package com.app.paperstow.data.demo

import android.content.Context
import com.app.paperstow.debug.DebugLogger
import com.app.paperstow.domain.model.Document
import com.app.paperstow.domain.model.Tag
import com.app.paperstow.domain.repository.DocumentFileStorage
import com.app.paperstow.domain.repository.DocumentRepository
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.first
import java.time.Instant
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class DemoDataRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val fileStorage: DocumentFileStorage,
    private val documentRepository: DocumentRepository
) {
    suspend fun demoDocuments(): List<Document> =
        documentRepository.getAll("default-member").first()
            .filter { doc -> doc.tags.any { it.name == DEMO_SYSTEM_TAG } }

    suspend fun isLoaded(): Boolean = demoDocuments().isNotEmpty()

    suspend fun importSampleTrip(): Result<Int> = runCatching {
        if (isLoaded()) return@runCatching demoDocuments().size
        var count = 0
        val now = Instant.now()
        DemoCatalog.items.forEach { item ->
            val bytes = context.assets.open("demo/${item.assetName}").use { it.readBytes() }
            val fileId = fileStorage.store("default-member", bytes, item.format).getOrThrow()
            val tags = (listOf(DEMO_SYSTEM_TAG, DEMO_FOLDER_TAG) + item.tags).distinct().map {
                Tag(name = it, isAutoGenerated = it == DEMO_SYSTEM_TAG)
            }
            documentRepository.insert(
                Document(
                    id = fileId,
                    memberId = "default-member",
                    type = item.type,
                    format = item.format,
                    originalFileName = item.fileName,
                    metadata = emptyMap(),
                    tags = tags,
                    createdAt = now,
                    updatedAt = now,
                    extractionConfidence = 1f,
                    requiresManualReview = false
                )
            ).getOrThrow()
            count++
        }
        DebugLogger.i("Demo", "Imported $count sample documents")
        count
    }

    suspend fun removeSampleTrip(): Result<Int> = runCatching {
        val docs = demoDocuments()
        docs.forEach { doc ->
            fileStorage.secureDelete(doc.id)
            documentRepository.delete(doc.id).getOrThrow()
        }
        DebugLogger.i("Demo", "Removed ${docs.size} sample documents")
        docs.size
    }
}
