package com.app.traveldocs.domain.properties

import com.app.traveldocs.data.local.TagRepositoryImpl
import com.app.traveldocs.data.local.dao.DocumentTagDao
import com.app.traveldocs.data.local.entity.DocumentTagEntity
import io.kotest.property.Arb
import io.kotest.property.arbitrary.arbitrary
import io.kotest.property.arbitrary.string
import io.kotest.property.checkAll
import io.mockk.coEvery
import io.mockk.mockk
import io.mockk.unmockkAll
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Property 13: Adding a tag grows the tag list
 *
 * For any document and any valid non-duplicate tag string, adding the tag should
 * increase the document's tag count by exactly one.
 *
 * **Validates: Requirements 6.2**
 */
@DisplayName("Property Test")
// Removed JUnitTag - invalid syntax
class TagAddGrowsListPropertyTest {

    private lateinit var documentTagDao: DocumentTagDao
    private lateinit var repository: TagRepositoryImpl

    // In-memory store simulating the database
    private val tagStore = mutableListOf<DocumentTagEntity>()

    @BeforeEach
    fun setUp() {
        tagStore.clear()
        documentTagDao = mockk(relaxed = true)

        // Mock getByDocumentId to return tags from in-memory store
        coEvery { documentTagDao.getByDocumentId(any()) } coAnswers {
            val documentId = firstArg<String>()
            tagStore.filter { it.documentId == documentId }
        }

        // Mock getCount to return tag count for a document
        coEvery { documentTagDao.getCount(any()) } coAnswers {
            val documentId = firstArg<String>()
            tagStore.count { it.documentId == documentId }
        }

        // Mock insert to add to in-memory store
        coEvery { documentTagDao.insert(any()) } coAnswers {
            val entity = firstArg<DocumentTagEntity>()
            // Simulate IGNORE conflict strategy: only insert if not already present
            val exists = tagStore.any { it.documentId == entity.documentId && it.tag == entity.tag }
            if (!exists) {
                tagStore.add(entity)
            }
        }

        repository = TagRepositoryImpl(documentTagDao)
    }

    @AfterEach
    fun tearDown() {
        unmockkAll()
    }

    // Generator for valid tag names (non-empty alphanumeric strings)
    private val arbTagName: Arb<String> = Arb.string(minSize = 1, maxSize = 30)

    // Generator for document IDs
    private val arbDocumentId: Arb<String> = arbitrary {
        "doc-${Arb.string(minSize = 5, maxSize = 10).bind()}"
    }

    @Test
    @DisplayName("Adding a non-duplicate tag to a document increases tag count by exactly one")
    fun `adding a non-duplicate tag increases tag count by one`() = runTest {
        checkAll(100, arbDocumentId, arbTagName) { documentId, tagName ->
            // Reset state for each iteration
            tagStore.clear()

            // Get initial tag count
            val initialTags = repository.getTagsForDocument(documentId)
            val initialCount = initialTags.size

            // Add a new tag
            val result = repository.addTag(documentId, tagName)

            // Verify it succeeded
            assertTrue(result.isSuccess, "Adding tag should succeed")

            // Get the new tag count
            val newTags = repository.getTagsForDocument(documentId)
            val newCount = newTags.size

            // Tag count should have increased by exactly one
            assertEquals(
                initialCount + 1,
                newCount,
                "Tag count should increase by 1 after adding '$tagName' to document '$documentId'"
            )
        }
    }

    @Test
    @DisplayName("Adding a non-duplicate tag to a document with existing tags increases count by one")
    fun `adding tag to document with existing tags increases count by one`() = runTest {
        checkAll(100, arbDocumentId, arbTagName) { documentId, newTagName ->
            // Reset and pre-populate with some existing tags
            tagStore.clear()

            // Add some pre-existing tags to the document (up to 5)
            val existingTagCount = (1..5).random()
            for (i in 1..existingTagCount) {
                tagStore.add(
                    DocumentTagEntity(
                        documentId = documentId,
                        tag = "existing-tag-$i",
                        isAutoGenerated = false,
                        createdAt = System.currentTimeMillis()
                    )
                )
            }

            // Ensure the new tag name doesn't collide with existing tags
            val uniqueTagName = "new-$newTagName"
            // Make sure no collision with existing tags
            val alreadyExists = tagStore.any { it.documentId == documentId && it.tag == uniqueTagName }
            if (alreadyExists) return@checkAll // Skip this iteration to avoid flaky test

            val initialCount = repository.getTagsForDocument(documentId).size
            assertEquals(existingTagCount, initialCount)

            // Add the new unique tag
            val result = repository.addTag(documentId, uniqueTagName)
            assertTrue(result.isSuccess, "Adding tag should succeed")

            // Verify count increased by exactly one
            val newCount = repository.getTagsForDocument(documentId).size
            assertEquals(
                initialCount + 1,
                newCount,
                "Tag count should increase by 1: was $initialCount, now $newCount"
            )
        }
    }

    @Test
    @DisplayName("Adding a tag when under the 20-tag limit succeeds and grows the list")
    fun `adding tag under limit succeeds and grows list`() = runTest {
        checkAll(100, arbDocumentId, arbTagName) { documentId, tagName ->
            // Reset and pre-populate with a random number of tags below the limit
            tagStore.clear()

            val existingCount = (0..18).random() // 0 to 18 existing tags (under limit of 20)
            for (i in 1..existingCount) {
                tagStore.add(
                    DocumentTagEntity(
                        documentId = documentId,
                        tag = "prefilled-tag-$i",
                        isAutoGenerated = false,
                        createdAt = System.currentTimeMillis()
                    )
                )
            }

            // Use a guaranteed unique tag name
            val uniqueTag = "unique-${tagName.hashCode()}"
            val alreadyExists = tagStore.any { it.documentId == documentId && it.tag == uniqueTag }
            if (alreadyExists) return@checkAll

            val initialCount = repository.getTagsForDocument(documentId).size

            // Add the new tag
            val result = repository.addTag(documentId, uniqueTag)
            assertTrue(result.isSuccess, "Adding tag under limit should succeed")

            // Verify count grew by one
            val newCount = repository.getTagsForDocument(documentId).size
            assertEquals(
                initialCount + 1,
                newCount,
                "Count should grow by 1 when adding under limit (existing: $existingCount)"
            )
        }
    }
}
