package com.app.paperstow.domain.usecase

import com.app.paperstow.debug.DebugLogger
import com.app.paperstow.domain.model.Document
import com.app.paperstow.domain.model.DocumentType
import com.app.paperstow.domain.model.ExtractionResult
import com.app.paperstow.domain.model.ImportedDocument
import com.app.paperstow.domain.model.MetadataField
import com.app.paperstow.domain.model.Tag
import com.app.paperstow.domain.repository.AutoTagGenerator
import com.app.paperstow.domain.repository.DocumentFileStorage
import com.app.paperstow.domain.repository.DocumentRepository
import com.app.paperstow.domain.repository.MetadataExtractor
import dagger.hilt.android.qualifiers.ApplicationContext
import android.content.Context
import java.time.Instant
import java.util.UUID
import javax.inject.Inject

/**
 * The heart of the import pipeline.
 *
 * Takes raw bytes from whatever source (camera, file picker, Drive, URL) and runs them
 * through: storage → OCR extraction → auto-tagging → database insert.
 *
 * Each step degrades gracefully — if OCR fails, we still store the doc. If tagging fails,
 * we still have the doc with whatever metadata we got. The user never sees a failed import
 * unless the file itself can't be written to disk.
 *
 * Pipeline steps are logged extensively for debugging large imports.
 */
class DocumentImportUseCase @Inject constructor(
    @ApplicationContext private val context: Context,
    private val fileStorage: DocumentFileStorage,
    private val metadataExtractor: MetadataExtractor,
    private val documentRepository: DocumentRepository,
    private val autoTagGenerator: AutoTagGenerator
) {

    suspend fun importAndProcess(
        importedDocument: ImportedDocument,
        memberId: String
    ): Result<Document> {
        val startTime = System.currentTimeMillis()
        DebugLogger.i("Import", "═══ Pipeline started: format=${importedDocument.format}, size=${importedDocument.rawBytes.size} bytes, member=$memberId")

        // Step 1: Store the raw file
        DebugLogger.d("Import", "Step 1: Storing file...")
        val fileId = fileStorage.store(memberId, importedDocument.rawBytes, importedDocument.format)
            .getOrElse { e ->
                DebugLogger.e("Import", "Step 1 FAILED: File storage error", e)
                return Result.failure(e)
            }
        DebugLogger.i("Import", "Step 1 OK: fileId=$fileId")

        // Step 2: Extract metadata (graceful degradation on failure)
        DebugLogger.d("Import", "Step 2: Extracting metadata via ML Kit OCR...")
        val extractionResult = try {
            val result = ocrDocument(importedDocument.format, importedDocument.rawBytes)
            if (result != null) {
                DebugLogger.i("Import", "Step 2 OK: type=${result.documentType}, confidence=${result.confidence}, fields=${result.metadata.size}, textChars=${result.rawText.length}")
            } else {
                DebugLogger.w("Import", "Step 2: No OCR text (format=${importedDocument.format})")
            }
            result
        } catch (e: Exception) {
            DebugLogger.e("Import", "Step 2 FAILED: Extraction threw exception (graceful degradation)", e)
            null
        }

        // Step 3: Generate auto-tags (graceful degradation on failure)
        DebugLogger.d("Import", "Step 3: Generating auto-tags...")
        val autoTags = try {
            if (extractionResult != null) {
                val tags = autoTagGenerator.generateTags(extractionResult.documentType, extractionResult.metadata)
                    .map { Tag(name = it, isAutoGenerated = true) }
                DebugLogger.i("Import", "Step 3 OK: tags=${tags.map { it.name }}")
                tags
            } else {
                DebugLogger.d("Import", "Step 3: Skipped (no extraction result)")
                emptyList()
            }
        } catch (e: Exception) {
            DebugLogger.e("Import", "Step 3 FAILED: Tag generation threw (graceful degradation)", e)
            emptyList()
        }

        // Step 3b: Tag unsupported formats so they're easy to find
        val formatTags = if (importedDocument.format == com.app.paperstow.domain.model.DocumentFormat.AUDIO) {
            autoTags + com.app.paperstow.domain.model.Tag(name = "__AUDIO", isAutoGenerated = true)
        } else if (importedDocument.format == com.app.paperstow.domain.model.DocumentFormat.UNKNOWN) {
            autoTags + com.app.paperstow.domain.model.Tag(name = "__UNSUPPORTED", isAutoGenerated = true)
        } else autoTags

        // Step 4: Build and store the Document
        DebugLogger.d("Import", "Step 4: Storing document in repository...")
        val now = Instant.now()
        val document = Document(
            id = fileId,
            memberId = memberId,
            type = extractionResult?.documentType ?: DocumentType.UNKNOWN,
            format = importedDocument.format,
            originalFileName = importedDocument.originalFileName,
            metadata = extractionResult?.metadata?.mapValues { it.value.value } ?: emptyMap(),
            tags = formatTags,
            createdAt = now,
            updatedAt = now,
            extractionConfidence = extractionResult?.confidence,
            requiresManualReview = extractionResult?.requiresManualReview ?: true
        )

        val insertResult = documentRepository.insert(document)
        insertResult.onSuccess {
            val indexText = com.app.paperstow.data.local.SearchIndex.textForImport(
                importedDocument.format,
                importedDocument.rawBytes,
                extractionResult?.rawText.orEmpty()
            )
            if (indexText.isNotBlank()) {
                documentRepository.updateOcrText(document.id, indexText)
            }
        }
        val elapsed = System.currentTimeMillis() - startTime
        insertResult.onSuccess {
            DebugLogger.i("Import", "═══ Pipeline COMPLETE in ${elapsed}ms: docId=${document.id}, type=${document.type}")
        }
        insertResult.onFailure { e ->
            DebugLogger.e("Import", "═══ Pipeline FAILED at Step 4 after ${elapsed}ms: repository insert error", e)
        }
        return insertResult.map { document }
    }

    private suspend fun ocrDocument(
        format: com.app.paperstow.domain.model.DocumentFormat,
        bytes: ByteArray
    ): ExtractionResult? {
        val pages = com.app.paperstow.data.local.SearchIndex.imagesForOcr(format, bytes, context.cacheDir)
        if (pages.isEmpty()) return null
        val results = pages.mapNotNull { page ->
            val outcome = metadataExtractor.extract(page)
            outcome.onFailure { e -> DebugLogger.w("Import", "OCR page failed: ${e.message}") }
            outcome.getOrNull()
        }
        if (results.isEmpty()) return null
        val best = results.maxBy { it.confidence }
        val combined = results.joinToString("\n\n") { it.rawText }.trim()
        return best.copy(rawText = combined)
    }
}
