package com.app.traveldocs.domain.usecase

import com.app.traveldocs.domain.model.DocumentFormat
import com.app.traveldocs.domain.model.DocumentType
import com.app.traveldocs.domain.model.ExtractionResult
import com.app.traveldocs.domain.model.ExtractedValue
import com.app.traveldocs.domain.model.ImportedDocument
import com.app.traveldocs.domain.model.MetadataField
import com.app.traveldocs.domain.model.Tag
import com.app.traveldocs.domain.repository.AutoTagGenerator
import com.app.traveldocs.domain.repository.DocumentFileStorage
import com.app.traveldocs.domain.repository.DocumentRepository
import com.app.traveldocs.domain.repository.MetadataExtractor
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

@DisplayName("DocumentImportUseCase")
class DocumentImportUseCaseTest {

    private lateinit var fileStorage: DocumentFileStorage
    private lateinit var metadataExtractor: MetadataExtractor
    private lateinit var documentRepository: DocumentRepository
    private lateinit var autoTagGenerator: AutoTagGenerator
    private lateinit var useCase: DocumentImportUseCase

    private val memberId = "member-123"
    private val fileId = "file-456"
    private val testBytes = byteArrayOf(0x25, 0x50, 0x44, 0x46) // PDF magic bytes
    private val importedDocument = ImportedDocument(
        rawBytes = testBytes,
        format = DocumentFormat.PDF,
        originalFileName = "passport.pdf"
    )

    @BeforeEach
    fun setUp() {
        fileStorage = mockk()
        metadataExtractor = mockk()
        documentRepository = mockk()
        autoTagGenerator = mockk()
        useCase = DocumentImportUseCase(fileStorage, metadataExtractor, documentRepository, autoTagGenerator)
    }

    @Nested
    @DisplayName("Successful import with extraction")
    inner class SuccessfulImport {

        @Test
        fun `stores file and returns document with extracted metadata`() = runTest {
            val extractionResult = ExtractionResult(
                documentType = DocumentType.PASSPORT,
                metadata = mapOf(
                    MetadataField.ID_NUMBER to ExtractedValue("AB123456", 0.95f),
                    MetadataField.HOLDER_NAME to ExtractedValue("John Doe", 0.9f),
                    MetadataField.EXPIRY_DATE to ExtractedValue("01/01/2030", 0.85f)
                ),
                confidence = 0.9f,
                requiresManualReview = false
            )
            val tags = listOf("passport", "2030")

            coEvery { fileStorage.store(memberId, testBytes, DocumentFormat.PDF) } returns Result.success(fileId)
            coEvery { metadataExtractor.extract(testBytes) } returns Result.success(extractionResult)
            every { autoTagGenerator.generateTags(DocumentType.PASSPORT, extractionResult.metadata) } returns tags
            coEvery { documentRepository.insert(any()) } returns Result.success("doc-id")

            val result = useCase.importAndProcess(importedDocument, memberId)

            assertTrue(result.isSuccess)
            val document = result.getOrThrow()
            assertEquals(DocumentType.PASSPORT, document.type)
            assertEquals(DocumentFormat.PDF, document.format)
            assertEquals("passport.pdf", document.originalFileName)
            assertEquals(memberId, document.memberId)
            assertEquals("AB123456", document.metadata[MetadataField.ID_NUMBER])
            assertEquals("John Doe", document.metadata[MetadataField.HOLDER_NAME])
            assertEquals("01/01/2030", document.metadata[MetadataField.EXPIRY_DATE])
            assertEquals(0.9f, document.extractionConfidence)
            assertEquals(false, document.requiresManualReview)
            assertEquals(2, document.tags.size)
            assertTrue(document.tags.all { it.isAutoGenerated })
            assertTrue(document.tags.any { it.name == "passport" })
            assertTrue(document.tags.any { it.name == "2030" })
        }

        @Test
        fun `stores document in repository`() = runTest {
            val extractionResult = ExtractionResult(
                documentType = DocumentType.VISA,
                metadata = mapOf(
                    MetadataField.VISA_NUMBER to ExtractedValue("V123456", 0.9f)
                ),
                confidence = 0.85f,
                requiresManualReview = false
            )

            coEvery { fileStorage.store(memberId, testBytes, DocumentFormat.PDF) } returns Result.success(fileId)
            coEvery { metadataExtractor.extract(testBytes) } returns Result.success(extractionResult)
            every { autoTagGenerator.generateTags(DocumentType.VISA, extractionResult.metadata) } returns listOf("visa")
            coEvery { documentRepository.insert(any()) } returns Result.success("doc-id")

            useCase.importAndProcess(importedDocument, memberId)

            coVerify(exactly = 1) { documentRepository.insert(any()) }
        }
    }

    @Nested
    @DisplayName("Graceful degradation on extraction failure")
    inner class ExtractionFailure {

        @Test
        fun `stores document with UNKNOWN type when extraction returns failure`() = runTest {
            coEvery { fileStorage.store(memberId, testBytes, DocumentFormat.PDF) } returns Result.success(fileId)
            coEvery { metadataExtractor.extract(testBytes) } returns Result.failure(RuntimeException("OCR failed"))
            coEvery { documentRepository.insert(any()) } returns Result.success("doc-id")

            val result = useCase.importAndProcess(importedDocument, memberId)

            assertTrue(result.isSuccess)
            val document = result.getOrThrow()
            assertEquals(DocumentType.UNKNOWN, document.type)
            assertTrue(document.metadata.isEmpty())
            assertTrue(document.tags.isEmpty())
            assertEquals(null, document.extractionConfidence)
            assertTrue(document.requiresManualReview)
        }

        @Test
        fun `stores document when extraction throws exception`() = runTest {
            coEvery { fileStorage.store(memberId, testBytes, DocumentFormat.PDF) } returns Result.success(fileId)
            coEvery { metadataExtractor.extract(testBytes) } throws RuntimeException("Unexpected error")
            coEvery { documentRepository.insert(any()) } returns Result.success("doc-id")

            val result = useCase.importAndProcess(importedDocument, memberId)

            assertTrue(result.isSuccess)
            val document = result.getOrThrow()
            assertEquals(DocumentType.UNKNOWN, document.type)
            assertTrue(document.metadata.isEmpty())
            assertTrue(document.tags.isEmpty())
            assertTrue(document.requiresManualReview)
        }

        @Test
        fun `stores document with extracted metadata but empty tags when tag generation fails`() = runTest {
            val extractionResult = ExtractionResult(
                documentType = DocumentType.TICKET,
                metadata = mapOf(
                    MetadataField.BOOKING_REFERENCE to ExtractedValue("ABC123", 0.9f)
                ),
                confidence = 0.85f,
                requiresManualReview = false
            )

            coEvery { fileStorage.store(memberId, testBytes, DocumentFormat.PDF) } returns Result.success(fileId)
            coEvery { metadataExtractor.extract(testBytes) } returns Result.success(extractionResult)
            every { autoTagGenerator.generateTags(DocumentType.TICKET, extractionResult.metadata) } throws RuntimeException("Tag generation error")
            coEvery { documentRepository.insert(any()) } returns Result.success("doc-id")

            val result = useCase.importAndProcess(importedDocument, memberId)

            assertTrue(result.isSuccess)
            val document = result.getOrThrow()
            assertEquals(DocumentType.TICKET, document.type)
            assertEquals("ABC123", document.metadata[MetadataField.BOOKING_REFERENCE])
            assertTrue(document.tags.isEmpty())
            assertEquals(0.85f, document.extractionConfidence)
        }
    }

    @Nested
    @DisplayName("File storage failure")
    inner class FileStorageFailure {

        @Test
        fun `returns failure when file storage fails`() = runTest {
            val storageError = RuntimeException("Disk full")
            coEvery { fileStorage.store(memberId, testBytes, DocumentFormat.PDF) } returns Result.failure(storageError)

            val result = useCase.importAndProcess(importedDocument, memberId)

            assertTrue(result.isFailure)
            assertEquals("Disk full", result.exceptionOrNull()?.message)
        }

        @Test
        fun `does not attempt extraction when file storage fails`() = runTest {
            coEvery { fileStorage.store(memberId, testBytes, DocumentFormat.PDF) } returns Result.failure(RuntimeException("Storage error"))

            useCase.importAndProcess(importedDocument, memberId)

            coVerify(exactly = 0) { metadataExtractor.extract(any()) }
        }
    }

    @Nested
    @DisplayName("Repository insertion failure")
    inner class RepositoryFailure {

        @Test
        fun `returns failure when repository insert fails`() = runTest {
            val extractionResult = ExtractionResult(
                documentType = DocumentType.PASSPORT,
                metadata = emptyMap(),
                confidence = 0.5f,
                requiresManualReview = true
            )

            coEvery { fileStorage.store(memberId, testBytes, DocumentFormat.PDF) } returns Result.success(fileId)
            coEvery { metadataExtractor.extract(testBytes) } returns Result.success(extractionResult)
            every { autoTagGenerator.generateTags(DocumentType.PASSPORT, emptyMap()) } returns emptyList()
            coEvery { documentRepository.insert(any()) } returns Result.failure(RuntimeException("DB error"))

            val result = useCase.importAndProcess(importedDocument, memberId)

            assertTrue(result.isFailure)
            assertEquals("DB error", result.exceptionOrNull()?.message)
        }
    }

    @Nested
    @DisplayName("Low confidence extraction")
    inner class LowConfidenceExtraction {

        @Test
        fun `flags document for manual review when confidence below 0_8`() = runTest {
            val extractionResult = ExtractionResult(
                documentType = DocumentType.PASSPORT,
                metadata = mapOf(
                    MetadataField.ID_NUMBER to ExtractedValue("AB123", 0.5f)
                ),
                confidence = 0.4f,
                requiresManualReview = true
            )

            coEvery { fileStorage.store(memberId, testBytes, DocumentFormat.PDF) } returns Result.success(fileId)
            coEvery { metadataExtractor.extract(testBytes) } returns Result.success(extractionResult)
            every { autoTagGenerator.generateTags(DocumentType.PASSPORT, extractionResult.metadata) } returns listOf("passport")
            coEvery { documentRepository.insert(any()) } returns Result.success("doc-id")

            val result = useCase.importAndProcess(importedDocument, memberId)

            assertTrue(result.isSuccess)
            val document = result.getOrThrow()
            assertTrue(document.requiresManualReview)
            assertEquals(0.4f, document.extractionConfidence)
        }
    }
}
