package com.app.paperstow.data.local

import com.app.paperstow.data.local.dao.DocumentTagDao
import com.app.paperstow.data.local.entity.DocumentTagEntity
import com.app.paperstow.domain.model.Tag
import com.app.paperstow.domain.repository.TagRepository
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class TagRepositoryImpl @Inject constructor(
    private val documentTagDao: DocumentTagDao
) : TagRepository {

    companion object {
        private const val MAX_TAGS_PER_DOCUMENT = 20
        const val CATALOG_DOCUMENT_ID = DocumentTagDao.CATALOG_DOCUMENT_ID
    }

    override suspend fun getTagsForDocument(documentId: String): List<Tag> {
        return documentTagDao.getByDocumentId(documentId).map { entity ->
            Tag(name = entity.tag, isAutoGenerated = entity.isAutoGenerated)
        }
    }

    override suspend fun addTag(documentId: String, tagName: String): Result<Unit> {
        return try {
            val currentCount = documentTagDao.getCount(documentId)
            if (currentCount >= MAX_TAGS_PER_DOCUMENT) {
                return Result.failure(IllegalStateException("Tag limit reached. Maximum $MAX_TAGS_PER_DOCUMENT tags per document."))
            }
            val existingTags = documentTagDao.getByDocumentId(documentId)
            if (existingTags.any { it.tag == tagName }) {
                return Result.success(Unit)
            }
            documentTagDao.insert(DocumentTagEntity(documentId = documentId, tag = tagName, isAutoGenerated = false, createdAt = System.currentTimeMillis()))
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun removeTag(documentId: String, tagName: String): Result<Unit> {
        // System tags (__ prefix) cannot be removed directly by the user.
        if (tagName.startsWith("__")) {
            return Result.failure(IllegalArgumentException("System tag '$tagName' cannot be removed manually"))
        }
        return try {
            documentTagDao.delete(documentId, tagName)
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun deleteTagGlobally(memberId: String, tagName: String): Result<Unit> {
        if (tagName.startsWith("__")) {
            return Result.failure(IllegalArgumentException("System tag '$tagName' cannot be deleted"))
        }
        return try {
            documentTagDao.deleteTagGlobally(memberId, tagName)
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getAllTags(memberId: String): List<Tag> {
        return documentTagDao.getAllTagsForMember(memberId)
            .map { entity -> Tag(name = entity.tag, isAutoGenerated = entity.isAutoGenerated) }
            .distinctBy { it.name }
    }

    override suspend fun createStandaloneTag(memberId: String, tagName: String): Result<Unit> {
        val name = tagName.trim()
        if (name.isEmpty()) {
            return Result.failure(IllegalArgumentException("Tag name is empty"))
        }
        if (name.startsWith("__")) {
            return Result.failure(IllegalArgumentException("System tag names are reserved"))
        }
        return try {
            val existing = documentTagDao.getAllTagsForMember(memberId).any { it.tag.equals(name, ignoreCase = false) }
            if (!existing) {
                documentTagDao.insert(
                    DocumentTagEntity(
                        documentId = CATALOG_DOCUMENT_ID,
                        tag = name,
                        isAutoGenerated = false,
                        createdAt = System.currentTimeMillis()
                    )
                )
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun getTagUsageCount(memberId: String, tagName: String): Int {
        return documentTagDao.getDocumentCountForTag(memberId, tagName)
    }

    suspend fun renameTag(memberId: String, oldName: String, newName: String): Result<Unit> {
        return try {
            documentTagDao.renameTag(memberId, oldName, newName)
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
