package com.app.traveldocs

import android.app.Application
import com.app.traveldocs.debug.CrashHandler
import com.app.traveldocs.debug.DebugLogger
import dagger.hilt.android.HiltAndroidApp

/**
 * Application entry point.
 *
 * Two things happen here at startup:
 * 1. Debug logger gets initialized (writes to logcat + file + in-memory buffer)
 * 2. Crash handler hooks into the uncaught exception pipeline so we never lose a stack trace
 *
 * Everything else (DI, Room, etc.) is handled by Hilt and lazy initialization.
 */
@HiltAndroidApp
class TravelDocsApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        DebugLogger.init(this)
        CrashHandler.install(this)
        DebugLogger.i("App", "Document Manager started. Build: ${BuildConfig.VERSION_NAME}")
        verifyDatabaseTables()
    }

    /**
     * Defensive check: ensure required Room tables exist.
     * If missing (e.g., after a failed restore), create them.
     * This prevents SQLiteException crashes on corrupted/missing schema.
     */
    private fun verifyDatabaseTables() {
        try {
            val dbFile = getDatabasePath("traveldocs.db")
            if (!dbFile.exists()) return // Room will create on first access

            val db = android.database.sqlite.SQLiteDatabase.openDatabase(dbFile.path, null, android.database.sqlite.SQLiteDatabase.OPEN_READWRITE)
            val cursor = db.rawQuery("SELECT name FROM sqlite_master WHERE type='table' AND name='documents'", null)
            val hasDocumentsTable = cursor.count > 0
            cursor.close()

            if (!hasDocumentsTable) {
                DebugLogger.w("App", "MISSING TABLE: 'documents' — creating schema defensively")
                db.execSQL("CREATE TABLE IF NOT EXISTS documents (id TEXT NOT NULL PRIMARY KEY, memberId TEXT NOT NULL, type TEXT NOT NULL, fileId TEXT NOT NULL, format TEXT NOT NULL, originalFileName TEXT, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL, extractionConfidence REAL, requiresManualReview INTEGER NOT NULL DEFAULT 0)")
                db.execSQL("CREATE TABLE IF NOT EXISTS document_metadata (id INTEGER PRIMARY KEY AUTOINCREMENT, documentId TEXT NOT NULL, field TEXT NOT NULL, value TEXT NOT NULL, confidence REAL NOT NULL)")
                db.execSQL("CREATE TABLE IF NOT EXISTS document_tags (documentId TEXT NOT NULL, tag TEXT NOT NULL, isAutoGenerated INTEGER NOT NULL, createdAt INTEGER NOT NULL, PRIMARY KEY(documentId, tag))")
                db.execSQL("CREATE TABLE IF NOT EXISTS family_members (id TEXT NOT NULL PRIMARY KEY, name TEXT NOT NULL, pinHash TEXT NOT NULL, pinSalt TEXT NOT NULL, createdAt INTEGER NOT NULL, failedAttempts INTEGER NOT NULL DEFAULT 0, lockedUntil INTEGER)")
                db.execSQL("CREATE TABLE IF NOT EXISTS gps_tracks (id INTEGER PRIMARY KEY AUTOINCREMENT, latitude REAL NOT NULL, longitude REAL NOT NULL, accuracy REAL NOT NULL, timestamp INTEGER NOT NULL, provider TEXT NOT NULL)")
                // Set Room's expected version so it doesn't trigger destructive migration
                db.execSQL("PRAGMA user_version = 2")
                DebugLogger.i("App", "Schema created defensively. Tables ready.")
                com.app.traveldocs.debug.UsageTelemetry.action("App", "defensive_schema_creation")
            }

            db.close()
        } catch (e: Exception) {
            DebugLogger.e("App", "Database verification failed (non-fatal)", e)
        }
    }
}
