package com.app.traveldocs.data.local

import androidx.room.withTransaction
import com.app.traveldocs.data.local.dao.DocumentDao
import com.app.traveldocs.data.local.dao.DocumentMetadataDao
import com.app.traveldocs.data.local.dao.DocumentTagDao
import com.app.traveldocs.data.local.entity.DocumentEntity
import com.app.traveldocs.data.local.entity.DocumentMetadataEntity
import com.app.traveldocs.data.local.entity.DocumentTagEntity
import com.app.traveldocs.domain.model.Document
import com.app.traveldocs.domain.model.DocumentFormat
import com.app.traveldocs.domain.model.DocumentType
import com.app.traveldocs.domain.model.MetadataField
import com.app.traveldocs.domain.model.SearchQuery
import com.app.traveldocs.domain.model.Tag
import com.app.traveldocs.domain.repository.DocumentRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.time.Instant
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class DocumentRepositoryImpl @Inject constructor(
    private val database: TravelDocsDatabase,
    private val documentDao: DocumentDao,
    private val documentMetadataDao: DocumentMetadataDao,
    private val documentTagDao: DocumentTagDao
) : DocumentRepository {

    companion object {
        private const val MAX_DOCUMENTS_PER_MEMBER = 100
    }

    override suspend fun getAll(memberId: String): Flow<List<Document>> {
        return documentDao.getAllByMemberId(memberId).map { entities ->
            entities.map { entity -> mapToDomain(entity) }
        }
    }

    override suspend fun getById(documentId: String): Document? {
        val entity = documentDao.getById(documentId) ?: return null
        return mapToDomain(entity)
    }

    override suspend fun insert(document: Document): Result<String> {
        return try {
            val currentCount = documentDao.getCount(document.memberId)
            if (currentCount >= MAX_DOCUMENTS_PER_MEMBER) {
                return Result.failure(
                    IllegalStateException(
                        "Document capacity limit reached. Maximum $MAX_DOCUMENTS_PER_MEMBER documents per member."
                    )
                )
            }

            database.withTransaction {
                val entity = mapToEntity(document)
                documentDao.insert(entity)

                val metadataEntities = document.metadata.map { (field, value) ->
                    DocumentMetadataEntity(
                        documentId = document.id,
                        field = field.name,
                        value = value,
                        confidence = document.extractionConfidence ?: 1.0f
                    )
                }
                if (metadataEntities.isNotEmpty()) {
                    documentMetadataDao.insertAll(metadataEntities)
                }

                val tagEntities = document.tags.map { tag ->
                    DocumentTagEntity(
                        documentId = document.id,
                        tag = tag.name,
                        isAutoGenerated = tag.isAutoGenerated,
                        createdAt = System.currentTimeMillis()
                    )
                }
                if (tagEntities.isNotEmpty()) {
                    documentTagDao.insertAll(tagEntities)
                }
            }

            Result.success(document.id)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun delete(documentId: String): Result<Unit> {
        return try {
            database.withTransaction {
                documentTagDao.deleteAllForDocument(documentId)
                documentMetadataDao.deleteByDocumentId(documentId)
                documentDao.delete(documentId)
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getCount(memberId: String): Int {
        return documentDao.getCount(memberId)
    }

    override suspend fun search(memberId: String, query: SearchQuery): List<Document> {
        val entities = when {
            query.tags.isNotEmpty() && query.freeText != null -> {
                documentDao.searchByTagsAndFreeText(
                    memberId = memberId,
                    tags = query.tags,
                    tagCount = query.tags.size,
                    freeText = query.freeText
                )
            }
            query.tags.isNotEmpty() -> {
                documentDao.searchByTags(
                    memberId = memberId,
                    tags = query.tags,
                    tagCount = query.tags.size
                )
            }
            query.freeText != null -> {
                documentDao.searchByFreeText(
                    memberId = memberId,
                    freeText = query.freeText
                )
            }
            else -> emptyList()
        }
        return entities.map { entity -> mapToDomain(entity) }
    }

    private suspend fun mapToDomain(entity: DocumentEntity): Document {
        val metadataEntities = documentMetadataDao.getByDocumentId(entity.id)
        val tagEntities = documentTagDao.getByDocumentId(entity.id)

        val metadata = metadataEntities.associate { meta ->
            val field = try {
                MetadataField.valueOf(meta.field)
            } catch (e: IllegalArgumentException) {
                null
            }
            field to meta.value
        }.filterKeys { it != null }.mapKeys { it.key!! }

        val tags = tagEntities.map { tagEntity ->
            Tag(name = tagEntity.tag, isAutoGenerated = tagEntity.isAutoGenerated)
        }

        return Document(
            id = entity.id,
            memberId = entity.memberId,
            type = try {
                DocumentType.valueOf(entity.type)
            } catch (e: IllegalArgumentException) {
                DocumentType.UNKNOWN
            },
            format = try {
                DocumentFormat.valueOf(entity.format)
            } catch (e: IllegalArgumentException) {
                DocumentFormat.PDF
            },
            originalFileName = entity.originalFileName,
            metadata = metadata,
            tags = tags,
            createdAt = Instant.ofEpochMilli(entity.createdAt),
            updatedAt = Instant.ofEpochMilli(entity.updatedAt),
            extractionConfidence = entity.extractionConfidence,
            requiresManualReview = entity.requiresManualReview
        )
    }

    private fun mapToEntity(document: Document): DocumentEntity {
        return DocumentEntity(
            id = document.id,
            memberId = document.memberId,
            type = document.type.name,
            fileId = document.id,
            format = document.format.name,
            originalFileName = document.originalFileName,
            createdAt = document.createdAt.toEpochMilli(),
            updatedAt = document.updatedAt.toEpochMilli(),
            extractionConfidence = document.extractionConfidence,
            requiresManualReview = document.requiresManualReview
        )
    }
}
