package com.app.traveldocs.data.local

import com.app.traveldocs.data.local.dao.DocumentTagDao
import com.app.traveldocs.data.local.entity.DocumentTagEntity
import com.app.traveldocs.domain.model.Tag
import com.app.traveldocs.domain.repository.TagRepository
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class TagRepositoryImpl @Inject constructor(
    private val documentTagDao: DocumentTagDao
) : TagRepository {

    companion object {
        private const val MAX_TAGS_PER_DOCUMENT = 20
    }

    override suspend fun getTagsForDocument(documentId: String): List<Tag> {
        return documentTagDao.getByDocumentId(documentId).map { entity ->
            Tag(name = entity.tag, isAutoGenerated = entity.isAutoGenerated)
        }
    }

    override suspend fun addTag(documentId: String, tagName: String): Result<Unit> {
        return try {
            val currentCount = documentTagDao.getCount(documentId)
            if (currentCount >= MAX_TAGS_PER_DOCUMENT) {
                return Result.failure(IllegalStateException("Tag limit reached. Maximum $MAX_TAGS_PER_DOCUMENT tags per document."))
            }
            val existingTags = documentTagDao.getByDocumentId(documentId)
            if (existingTags.any { it.tag == tagName }) {
                return Result.success(Unit)
            }
            documentTagDao.insert(DocumentTagEntity(documentId = documentId, tag = tagName, isAutoGenerated = false, createdAt = System.currentTimeMillis()))
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun removeTag(documentId: String, tagName: String): Result<Unit> {
        // System tags (__ prefix) cannot be removed directly by the user.
        // They are managed by their owning feature (e.g., PIN lock manages __PIN_PROTECTED).
        if (tagName.startsWith("__")) {
            return Result.failure(IllegalArgumentException("System tag '$tagName' cannot be removed manually"))
        }
        return try {
            documentTagDao.delete(documentId, tagName)
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun deleteTagGlobally(memberId: String, tagName: String): Result<Unit> {
        if (tagName.startsWith("__")) {
            return Result.failure(IllegalArgumentException("System tag '$tagName' cannot be deleted"))
        }
        return try {
            documentTagDao.deleteTagGlobally(memberId, tagName)
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getAllTags(memberId: String): List<Tag> {
        return documentTagDao.getAllTagsForMember(memberId)
            .map { entity -> Tag(name = entity.tag, isAutoGenerated = entity.isAutoGenerated) }
            .distinctBy { it.name }
    }

    suspend fun getTagUsageCount(memberId: String, tagName: String): Int {
        return documentTagDao.getDocumentCountForTag(memberId, tagName)
    }

    suspend fun renameTag(memberId: String, oldName: String, newName: String): Result<Unit> {
        return try {
            documentTagDao.renameTag(memberId, oldName, newName)
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
