package com.app.paperstow.presentation.tags

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.app.paperstow.data.local.TagRepositoryImpl
import com.app.paperstow.debug.DebugLogger
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

data class TagInfo(
    val name: String,
    val usageCount: Int,
    val isAutoGenerated: Boolean,
    val showOnHome: Boolean = true
)

@HiltViewModel
class TagManagementViewModel @Inject constructor(
    private val tagRepository: TagRepositoryImpl,
    private val tagLooks: com.app.paperstow.data.local.TagColorStore
) : ViewModel() {

    private val _tags = MutableStateFlow<List<TagInfo>>(emptyList())
    val tags: StateFlow<List<TagInfo>> = _tags.asStateFlow()

    private val _sortByCount = MutableStateFlow(false)
    val sortByCount: StateFlow<Boolean> = _sortByCount.asStateFlow()

    private val memberId = "default-member"

    init { loadTags() }

    fun loadTags() {
        viewModelScope.launch {
            val allTags = tagRepository.getAllTags(memberId).filter { !it.name.startsWith("__") }
            val tagInfos = allTags.map { tag ->
                val count = tagRepository.getTagUsageCount(memberId, tag.name)
                TagInfo(tag.name, count, tag.isAutoGenerated, tagLooks.isShownOnHome(tag.name))
            }
            _tags.value = if (_sortByCount.value) tagInfos.sortedByDescending { it.usageCount } else tagInfos.sortedBy { it.name }
            DebugLogger.d("TagMgmt", "Loaded ${tagInfos.size} tags")
        }
    }

    fun refresh() = loadTags()

    fun createTag(name: String) {
        if (name.isBlank()) return
        viewModelScope.launch {
            DebugLogger.i("TagMgmt", "Creating tag: '$name'")
            val result = tagRepository.createStandaloneTag(memberId, name.trim())
            result.onFailure { DebugLogger.e("TagMgmt", "Create tag failed: ${it.message}") }
            loadTags()
        }
    }

    fun renameTag(oldName: String, newName: String) {
        if (newName.isBlank() || oldName == newName) return
        viewModelScope.launch {
            DebugLogger.i("TagMgmt", "Renaming tag '$oldName' -> '$newName'")
            tagRepository.renameTag(memberId, oldName, newName)
            tagLooks.renameLook(oldName, newName)
            loadTags()
        }
    }

    fun deleteTag(tagName: String) {
        viewModelScope.launch {
            DebugLogger.w("TagMgmt", "Deleting tag '$tagName' globally")
            tagRepository.deleteTagGlobally(memberId, tagName)
            tagLooks.clearLook(tagName)
            loadTags()
        }
    }

    fun getUsageCount(tagName: String, callback: (Int) -> Unit) {
        viewModelScope.launch {
            val count = tagRepository.getTagUsageCount(memberId, tagName)
            callback(count)
        }
    }

    fun setShowOnHome(tagName: String, shown: Boolean) {
        tagLooks.setShownOnHome(tagName, shown)
        _tags.value = _tags.value.map { if (it.name == tagName) it.copy(showOnHome = shown) else it }
    }

    fun toggleSort() {
        _sortByCount.value = !_sortByCount.value
        val current = _tags.value
        _tags.value = if (_sortByCount.value) current.sortedByDescending { it.usageCount } else current.sortedBy { it.name }
    }
}
