#!/bin/bash
# Run all unit tests and generate a timestamped markdown report
# Usage: ./scripts/run-tests.sh
# Reports saved to: test-reports/YYYYMMDD_HHMMSS/

set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_DIR="$PROJECT_DIR/test-reports/$TIMESTAMP"
mkdir -p "$REPORT_DIR"

echo "=== Document Manager — Test Run ==="
echo "Timestamp: $TIMESTAMP"
echo "Report: $REPORT_DIR/REPORT.md"
echo ""

# Run tests
echo "Running unit tests..."
TEST_OUTPUT="$REPORT_DIR/raw_output.txt"
"$PROJECT_DIR/gradlew" -p "$PROJECT_DIR" testDebugUnitTest --no-daemon > "$TEST_OUTPUT" 2>&1
TEST_EXIT=$?

# Count results from Gradle XML reports
XML_DIR="$PROJECT_DIR/app/build/test-results/testDebugUnitTest"
TOTAL=0; PASSED=0; FAILED=0; SKIPPED=0
if [ -d "$XML_DIR" ]; then
    TOTAL=$(grep -r 'testcase' "$XML_DIR" --include="*.xml" | grep -c '<testcase')
    FAILED=$(grep -r '<failure' "$XML_DIR" --include="*.xml" | wc -l | tr -d ' ')
    SKIPPED=$(grep -r '<skipped' "$XML_DIR" --include="*.xml" | wc -l | tr -d ' ')
    PASSED=$((TOTAL - FAILED - SKIPPED))
fi

# Generate markdown report
cat > "$REPORT_DIR/REPORT.md" << EOF
# Test Report

**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Branch:** $(git -C "$PROJECT_DIR" branch --show-current 2>/dev/null || echo "N/A")
**Commit:** $(git -C "$PROJECT_DIR" rev-parse --short HEAD 2>/dev/null || echo "N/A")

## Summary

| Metric | Count |
|--------|-------|
| Total | $TOTAL |
| Passed | $PASSED |
| Failed | $FAILED |
| Skipped | $SKIPPED |
| **Result** | **$([ $TEST_EXIT -eq 0 ] && echo "✅ PASS" || echo "❌ FAIL")** |

## Test Classes

$(find "$XML_DIR" -name "*.xml" 2>/dev/null | while read f; do
    CLASS=$(grep -o 'classname="[^"]*"' "$f" | head -1 | sed 's/classname="//;s/"//')
    TESTS=$(grep -c '<testcase' "$f" 2>/dev/null || echo 0)
    FAILURES=$(grep -c '<failure' "$f" 2>/dev/null || echo 0)
    if [ "$FAILURES" -gt 0 ]; then
        echo "| ❌ $CLASS | $TESTS tests, $FAILURES failed |"
    else
        echo "| ✅ $CLASS | $TESTS tests |"
    fi
done | sort)

## Failed Tests

$(grep -r '<failure' "$XML_DIR" --include="*.xml" -A2 2>/dev/null | head -50 || echo "None")

---
*Generated by scripts/run-tests.sh*
EOF

echo ""
echo "=== Results ==="
echo "Total: $TOTAL | Passed: $PASSED | Failed: $FAILED | Skipped: $SKIPPED"
echo "Exit code: $TEST_EXIT"
echo "Report: $REPORT_DIR/REPORT.md"
echo ""

# Keep only last 10 reports
cd "$PROJECT_DIR/test-reports" && ls -dt */ 2>/dev/null | tail -n +11 | xargs rm -rf 2>/dev/null

exit $TEST_EXIT
