package com.app.paperstow.presentation.feedback

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.app.paperstow.data.feedback.FeedbackDraft
import com.app.paperstow.data.feedback.FeedbackDraftStore
import com.app.paperstow.data.local.InputSanitizer
import com.app.paperstow.debug.DebugLogger
import com.app.paperstow.domain.model.Document
import com.app.paperstow.domain.model.DocumentFormat
import com.app.paperstow.domain.model.DocumentType
import com.app.paperstow.domain.model.Tag
import com.app.paperstow.domain.repository.DocumentFileStorage
import com.app.paperstow.domain.repository.DocumentRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.time.Instant
import java.time.LocalDate
import javax.inject.Inject

const val APP_FEEDBACK_TAG = "App Feedbacks"

data class FeedbackUiState(
    val current: FeedbackDraft? = null,
    val drafts: List<FeedbackDraft> = emptyList(),
    val liked: String = "",
    val disliked: String = "",
    val message: String? = null,
    val busy: Boolean = false
)

@HiltViewModel
class FeedbackViewModel @Inject constructor(
    private val store: FeedbackDraftStore,
    private val fileStorage: DocumentFileStorage,
    private val documentRepository: DocumentRepository
) : ViewModel() {

    private val _state = MutableStateFlow(FeedbackUiState())
    val state: StateFlow<FeedbackUiState> = _state.asStateFlow()

    init {
        val current = store.currentOrNew()
        _state.value = FeedbackUiState(
            current = current,
            drafts = store.draftsNewestFirst(),
            liked = current.liked,
            disliked = current.disliked
        )
    }

    fun updateLiked(value: String) {
        _state.value = _state.value.copy(liked = value)
        persist()
    }

    fun updateDisliked(value: String) {
        _state.value = _state.value.copy(disliked = value)
        persist()
    }

    fun openDraft(id: String) {
        persist()
        store.setCurrent(id)
        val draft = store.get(id) ?: return
        _state.value = _state.value.copy(
            current = draft,
            drafts = store.draftsNewestFirst(),
            liked = draft.liked,
            disliked = draft.disliked,
            message = null
        )
    }

    fun newDraft() {
        persist()
        val draft = store.startNew()
        _state.value = _state.value.copy(
            current = draft,
            drafts = store.draftsNewestFirst(),
            liked = draft.liked,
            disliked = draft.disliked,
            message = "Started a new draft. Earlier drafts are still on this phone."
        )
    }

    fun deleteDraft(id: String) {
        store.delete(id)
        val current = store.currentOrNew()
        _state.value = _state.value.copy(
            current = current,
            drafts = store.draftsNewestFirst(),
            liked = current.liked,
            disliked = current.disliked,
            message = "Draft deleted. It stayed on this phone only."
        )
    }

    fun saveAsNote(onSaved: (Document) -> Unit) {
        persist()
        val draft = store.currentOrNew()
        if (draft.isBlank()) {
            _state.value = _state.value.copy(message = "Write something first.")
            return
        }
        viewModelScope.launch {
            _state.value = _state.value.copy(busy = true, message = null)
            try {
                val title = "Feedback ${LocalDate.now()}"
                val name = InputSanitizer.sanitizeFilename(title).let {
                    if (it.endsWith(".txt", true)) it else "$it.txt"
                }
                val bytes = draft.asNoteBody().toByteArray(Charsets.UTF_8)
                val fileId = fileStorage.store("default-member", bytes, DocumentFormat.TEXT).getOrThrow()
                val now = Instant.now()
                val document = Document(
                    id = fileId,
                    memberId = "default-member",
                    type = DocumentType.UNKNOWN,
                    format = DocumentFormat.TEXT,
                    originalFileName = name,
                    metadata = emptyMap(),
                    tags = listOf(
                        Tag(name = "Notes", isAutoGenerated = false),
                        Tag(name = APP_FEEDBACK_TAG, isAutoGenerated = false)
                    ),
                    createdAt = now,
                    updatedAt = now,
                    extractionConfidence = 1f,
                    requiresManualReview = false
                )
                documentRepository.insert(document).getOrThrow()
                store.delete(draft.id)
                val current = store.currentOrNew()
                _state.value = FeedbackUiState(
                    current = current,
                    drafts = store.draftsNewestFirst(),
                    liked = current.liked,
                    disliked = current.disliked,
                    message = "Saved as a note in $APP_FEEDBACK_TAG."
                )
                onSaved(document)
            } catch (e: Exception) {
                DebugLogger.e("Feedback", "Save as note failed", e)
                _state.value = _state.value.copy(busy = false, message = e.message ?: "Could not save as a note")
            }
        }
    }

    fun dismissMessage() {
        _state.value = _state.value.copy(message = null)
    }

    fun currentDraft(): FeedbackDraft = store.saveCurrent(_state.value.liked, _state.value.disliked)

    private fun persist() {
        val draft = store.saveCurrent(_state.value.liked, _state.value.disliked)
        _state.value = _state.value.copy(
            current = draft,
            drafts = store.draftsNewestFirst()
        )
    }
}
