package com.app.traveldocs.data.local.storage

import com.app.traveldocs.debug.DebugLogger
import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import com.app.traveldocs.domain.model.DocumentFormat
import com.app.traveldocs.domain.repository.DocumentFileStorage
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.security.KeyStore
import java.security.SecureRandom
import java.util.UUID
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Implements [DocumentFileStorage] with AES-256-GCM encryption for document files.
 *
 * Files are stored as `{file_id}.enc` under `files/docs/{member_id}/`.
 * Each encrypted file has a 12-byte IV prepended to the ciphertext.
 * The encryption key is stored in Android KeyStore and generated on first use.
 *
 * Secure deletion overwrites file contents with random bytes before deleting.
 */
@Singleton
class DocumentFileStorageImpl @Inject constructor(
    @ApplicationContext private val context: Context
) : DocumentFileStorage {

    companion object {
        private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
        private const val KEY_ALIAS = "travel_docs_file_encryption_key"
        private const val GCM_IV_LENGTH = 12
        private const val GCM_TAG_LENGTH = 128
        private const val DOCS_DIR = "docs"
        private const val FILE_EXTENSION = ".enc"
    }

    override suspend fun store(
        memberId: String,
        fileData: ByteArray,
        format: DocumentFormat
    ): Result<String> = runCatching {
        DebugLogger.d("FileStorage", "store: member=$memberId, format=$format, size=${fileData.size} bytes")
        val fileId = UUID.randomUUID().toString()
        val memberDir = getMemberDir(memberId)
        memberDir.mkdirs()

        val encryptedData = encrypt(fileData)
        val file = File(memberDir, "$fileId$FILE_EXTENSION")
        file.writeBytes(encryptedData)

        fileId
    }

    override suspend fun retrieve(fileId: String): Result<ByteArray> = runCatching {
        DebugLogger.d("FileStorage", "retrieve: fileId=$fileId")
        val file = findFile(fileId)
            ?: throw IllegalArgumentException("File not found: $fileId")

        val encryptedData = file.readBytes()
        decrypt(encryptedData)
    }

    override suspend fun secureDelete(fileId: String): Result<Unit> = runCatching {
        DebugLogger.w("FileStorage", "secureDelete: fileId=$fileId (overwrite + delete)")
        val file = findFile(fileId)
            ?: throw IllegalArgumentException("File not found: $fileId")

        // Overwrite with random bytes of the same size
        val random = SecureRandom()
        val randomBytes = ByteArray(file.length().toInt())
        random.nextBytes(randomBytes)
        file.writeBytes(randomBytes)

        // Delete the file
        if (!file.delete()) {
            throw IllegalStateException("Failed to delete file: $fileId")
        }
    }

    private fun encrypt(data: ByteArray): ByteArray {
        val key = getOrCreateKey()
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key)

        val iv = cipher.iv // 12 bytes generated by the cipher
        val ciphertext = cipher.doFinal(data)

        // Prepend IV to ciphertext: [IV (12 bytes)][ciphertext + GCM tag]
        return iv + ciphertext
    }

    private fun decrypt(encryptedData: ByteArray): ByteArray {
        require(encryptedData.size > GCM_IV_LENGTH) {
            "Encrypted data too short to contain IV"
        }

        val iv = encryptedData.copyOfRange(0, GCM_IV_LENGTH)
        val ciphertext = encryptedData.copyOfRange(GCM_IV_LENGTH, encryptedData.size)

        val key = getOrCreateKey()
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        val spec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
        cipher.init(Cipher.DECRYPT_MODE, key, spec)

        return cipher.doFinal(ciphertext)
    }

    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER)
        keyStore.load(null)

        if (!keyStore.containsAlias(KEY_ALIAS)) {
            generateKey()
        }

        val entry = keyStore.getEntry(KEY_ALIAS, null) as KeyStore.SecretKeyEntry
        return entry.secretKey
    }

    private fun generateKey() {
        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            KEYSTORE_PROVIDER
        )

        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setKeySize(256)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .build()

        keyGenerator.init(spec)
        keyGenerator.generateKey()
    }

    private fun getMemberDir(memberId: String): File {
        return File(context.filesDir, "$DOCS_DIR${File.separator}$memberId")
    }

    private fun findFile(fileId: String): File? {
        val fileName = "$fileId$FILE_EXTENSION"
        val docsRoot = File(context.filesDir, DOCS_DIR)
        if (!docsRoot.exists()) return null

        // Scan member directories for the file
        docsRoot.listFiles()?.forEach { memberDir ->
            if (memberDir.isDirectory) {
                val file = File(memberDir, fileName)
                if (file.exists()) return file
            }
        }
        return null
    }
}
