package com.app.paperstow.presentation.documents

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.app.paperstow.data.local.InputSanitizer
import com.app.paperstow.debug.DebugLogger
import com.app.paperstow.domain.model.Document
import com.app.paperstow.domain.model.DocumentFormat
import com.app.paperstow.domain.model.DocumentType
import com.app.paperstow.domain.model.Tag
import com.app.paperstow.domain.repository.DocumentFileStorage
import com.app.paperstow.domain.repository.DocumentRepository
import com.app.paperstow.domain.repository.TagRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.time.Instant
import java.time.LocalDate
import javax.inject.Inject

@HiltViewModel
class TextNoteViewModel @Inject constructor(
    private val fileStorage: DocumentFileStorage,
    private val documentRepository: DocumentRepository,
    private val tagRepository: TagRepository
) : ViewModel() {

    private val _saving = MutableStateFlow(false)
    val saving: StateFlow<Boolean> = _saving.asStateFlow()

    private val _error = MutableStateFlow<String?>(null)
    val error: StateFlow<String?> = _error.asStateFlow()

    private val _catalog = MutableStateFlow<List<String>>(emptyList())
    val catalog: StateFlow<List<String>> = _catalog.asStateFlow()

    init {
        viewModelScope.launch {
            _catalog.value = tagRepository.getAllTags("default-member")
                .map { it.name }
                .filter { !it.startsWith("__") }
                .distinct()
                .sorted()
        }
    }

    fun createNote(title: String, body: String, tags: List<String>, onSaved: (Document) -> Unit) {
        create(title, body, DocumentFormat.TEXT, tags, onSaved)
    }

    fun createChecklist(title: String, body: String, tags: List<String>, onSaved: (Document) -> Unit) {
        create(title, body, DocumentFormat.MARKDOWN, tags, onSaved)
    }

    fun updateNote(document: Document, title: String, body: String, tags: List<String>, onSaved: (Document) -> Unit) {
        updateDocument(document, title, body, tags, onSaved)
    }

    fun updateDocument(document: Document, title: String, body: String, tags: List<String>, onSaved: (Document) -> Unit) {
        viewModelScope.launch {
            _saving.value = true
            _error.value = null
            try {
                val name = displayName(title, document.format, document.originalFileName)
                fileStorage.replace(document.id, body.toByteArray(Charsets.UTF_8)).getOrThrow()
                val updatedAt = Instant.now()
                documentRepository.updateName(document.id, name, updatedAt).getOrThrow()
                documentRepository.updateOcrText(document.id, body)
                val applied = applyTags(document.id, document.tags, tags)
                val updated = document.copy(originalFileName = name, updatedAt = updatedAt, tags = applied)
                DebugLogger.i("Note", "Updated ${document.format} ${document.id}")
                onSaved(updated)
            } catch (e: Exception) {
                DebugLogger.e("Note", "Update failed", e)
                _error.value = e.message ?: "Could not save"
            } finally {
                _saving.value = false
            }
        }
    }

    private fun create(
        title: String,
        body: String,
        format: DocumentFormat,
        tags: List<String>,
        onSaved: (Document) -> Unit
    ) {
        viewModelScope.launch {
            _saving.value = true
            _error.value = null
            try {
                val name = displayName(title, format)
                val bytes = body.toByteArray(Charsets.UTF_8)
                val fileId = fileStorage.store("default-member", bytes, format).getOrThrow()
                val now = Instant.now()
                val chosen = sanitizeTagNames(tags)
                val document = Document(
                    id = fileId,
                    memberId = "default-member",
                    type = DocumentType.UNKNOWN,
                    format = format,
                    originalFileName = name,
                    metadata = emptyMap(),
                    tags = chosen.map { Tag(name = it, isAutoGenerated = false) },
                    createdAt = now,
                    updatedAt = now,
                    extractionConfidence = 1f,
                    requiresManualReview = false
                )
                documentRepository.insert(document).getOrThrow()
                documentRepository.updateOcrText(document.id, body)
                DebugLogger.i("Note", "Created ${format.name} ${document.id} ($name) tags=$chosen")
                onSaved(document)
            } catch (e: Exception) {
                DebugLogger.e("Note", "Create failed", e)
                _error.value = e.message ?: "Could not save"
            } finally {
                _saving.value = false
            }
        }
    }

    private suspend fun applyTags(documentId: String, previous: List<Tag>, desiredRaw: List<String>): List<Tag> {
        val desired = sanitizeTagNames(desiredRaw)
        val keepSystem = previous.filter { it.name.startsWith("__") }
        val currentUser = previous.filter { !it.name.startsWith("__") }.map { it.name }
        currentUser.filter { it !in desired }.forEach { tagRepository.removeTag(documentId, it) }
        desired.filter { it !in currentUser }.forEach { tagRepository.addTag(documentId, it) }
        return keepSystem + desired.map { Tag(name = it, isAutoGenerated = false) }
    }

    private fun sanitizeTagNames(tags: List<String>): List<String> =
        tags.map { InputSanitizer.sanitizeTag(it) }
            .filter { it.isNotBlank() && !it.startsWith("__") }
            .distinct()

    private fun displayName(title: String, format: DocumentFormat, fallback: String? = null): String {
        val ext = if (format == DocumentFormat.MARKDOWN) ".md" else ".txt"
        val raw = title.trim().ifBlank { fallback?.substringBeforeLast('.')?.ifBlank { null } }
            ?: if (format == DocumentFormat.MARKDOWN) "Plans ${LocalDate.now()}" else "Note ${LocalDate.now()}"
        val sanitized = InputSanitizer.sanitizeFilename(raw)
        return if (sanitized.endsWith(ext, ignoreCase = true)) sanitized else "$sanitized$ext"
    }
}
