package com.app.traveldocs.data.local.entity

import androidx.room.Entity

@Entity(tableName = "document_tags", primaryKeys = ["documentId", "tag"])
data class DocumentTagEntity(
    val documentId: String,
    val tag: String,
    val isAutoGenerated: Boolean,
    val createdAt: Long
)
